// Operation mapping for SAGE transactions
// Exported as default for use in 06-transactions.ts
const OP_MAP = {
    // Fleet Movement & State
    'createFleet': 'CreateFleet',
    'disbandFleet': 'DisbandFleet',
    'forceDisbandFleet': 'ForceDisbandFleet',
    'disbandedFleetToEscrow': 'DisbandedFleetToEscrow',
    'closeDisbandedFleet': 'CloseDisbandedFleet',
    'idleToLoadingBay': 'Dock',
    'loadingBayToIdle': 'Undock',
    'idleToRespawn': 'IdleToRespawn',
    'loadingBayToRespawn': 'LoadingBayToRespawn',
    'respawnToLoadingBay': 'Respawn',
    'mineAsteroidToRespawn': 'MineToRespawn',
    // Warp & Movement
    'startSubwarp': 'StartSubwarp',
    'stopSubwarp': 'StopSubwarp',
    'warpToCoordinate': 'WarpToCoord',
    'warpLane': 'WarpLane',
    'planetExitWarp': 'PlanetExitWarp',
    // Mining
    'startMiningAsteroid': 'StartMining',
    'stopMiningAsteroid': 'StopMining',
    // Scanning
    'scanForSurveyDataUnits': 'ScanSDU',
    'dropExpiredSurveyDataUnits': 'DropExpiredSDU',
    // Fleet Cargo Operations
    'depositCargoToFleet': 'LoadCargo',
    'withdrawCargoFromFleet': 'UnloadCargo',
    'transferCargoWithinFleet': 'TransferCargoFleet',
    // Game Cargo Operations  
    'depositCargoToGame': 'DepositCargoGame',
    'withdrawCargoFromGame': 'WithdrawCargoGame',
    // Starbase Cargo Operations
    'transferCargoAtStarbase': 'TransferCargoStarbase',
    'createCargoPod': 'CreateCargoPod',
    'removeCargoPod': 'RemoveCargoPod',
    // Fleet Management
    'addShipToFleet': 'AddShip',
    'addShipEscrowToFleet': 'AddShipEscrow',
    'removeShipEscrow': 'RemoveShipEscrow',
    'updateShipEscrow': 'UpdateShipEscrow',
    'updateShipInFleet': 'UpdateShipInFleet',
    'loadFleetCrew': 'LoadCrew',
    'unloadFleetCrew': 'UnloadCrew',
    'rearmFleet': 'Rearm',
    'refuelFleet': 'Refuel',
    // Crafting (add snake_case variants too)
    'createCraftingProcess': 'CraftStart',
    'create_crafting_process': 'CraftStart',
    'startCraftingProcess': 'CraftStart',
    'start_crafting_process': 'CraftStart',
    'stopCraftingProcess': 'CraftStop',
    'stop_crafting_process': 'CraftStop',
    'cancelCraftingProcess': 'CraftCancel',
    'cancel_crafting_process': 'CraftCancel',
    'closeCraftingProcess': 'CraftClose',
    'close_crafting_process': 'CraftClose',
    'claimCraftingOutputs': 'CraftClaim',
    'claim_crafting_outputs': 'CraftClaim',
    'claimCraftingNonConsumables': 'CraftClaimNonCons',
    'claim_non_consumable_ingredient': 'CraftClaimNonCons',
    'depositCraftingIngredient': 'CraftDeposit',
    'deposit_crafting_ingredient': 'CraftDeposit',
    'withdrawCraftingIngredient': 'CraftWithdraw',
    'withdraw_crafting_ingredient': 'CraftWithdraw',
    'burnCraftingConsumables': 'CraftBurn',
    'burn_consumable_ingredient': 'CraftBurn',
    'claim_recipe_output': 'CraftClaim',
    'claimRecipeOutput': 'CraftClaim',
    // Recipe & facility management mapped to generic 'Crafting' category
    'add_consumable_input_to_recipe': 'Crafting',
    'add_non_consumable_input_to_recipe': 'Crafting',
    'add_output_to_recipe': 'Crafting',
    'add_recipe_ingredient': 'Crafting',
    'remove_consumable_input_from_recipe': 'Crafting',
    'remove_non_consumable_input_from_recipe': 'Crafting',
    'remove_output_from_recipe': 'Crafting',
    'remove_recipe_ingredient': 'Crafting',
    'register_recipe': 'Crafting',
    'register_craftable_item': 'Crafting',
    'register_crafting_facility': 'Crafting',
    'register_recipe_category': 'Crafting',
    'register_crafting_facility_recipe_category': 'Crafting',
    'deregister_crafting_facility': 'Crafting',
    'deregister_recipe_category': 'Crafting',
    'legitimize_recipe_ingredient': 'Crafting',
    'drain_craftable_item_bank': 'Crafting',
    'initialize_domain': 'Crafting',
    'update_recipe': 'Crafting',
    'update_recipe_category': 'Crafting',
    'update_crafting_facility': 'Crafting',
    'remove_crafting_facility_recipe_category': 'Crafting',
    // Starbase Crafting
    'createStarbaseCraftingProcess': 'StarbaseCraftStart',
    'closeStarbaseCraftingProcess': 'StarbaseCraftClose',
    'closeResourceCraftingProcess': 'ResourceCraftClose',
    // Starbase Operations
    'startStarbaseUpgrade': 'StarbaseUpgradeStart',
    'completeStarbaseUpgrade': 'StarbaseUpgradeComplete',
    'submitStarbaseUpgradeResource': 'StarbaseUpgradeSubmit',
    'depositStarbaseUpkeepResource': 'StarbaseUpkeepDeposit',
    'registerStarbase': 'RegisterStarbase',
    'registerStarbasePlayer': 'RegisterStarbasePlayer',
    'deregisterStarbase': 'DeregisterStarbase',
    'updateStarbase': 'UpdateStarbase',
    // Crew
    'addCrewToGame': 'AddCrew',
    'removeCrewFromGame': 'RemoveCrew',
    'closePlayerCrewRecord': 'CloseCrewRecord',
    'registerSageCrewConfig': 'RegisterCrewConfig',
    'devAddCrewToGame': 'DevAddCrew',
    // Sector & Discovery
    'discoverSector': 'DiscoverSector',
    'registerSector': 'RegisterSector',
    'updateSector': 'UpdateSector',
    'addConnection': 'AddConnection',
    'removeConnection': 'RemoveConnection',
    // Resources & Mining Items
    'registerMineItem': 'RegisterMineItem',
    'deregisterMineItem': 'DeregisterMineItem',
    'updateMineItem': 'UpdateMineItem',
    'registerResource': 'RegisterResource',
    'deregisterResource': 'DeregisterResource',
    'updateResource': 'UpdateResource',
    // Ships
    'registerShip': 'RegisterShip',
    'setNextShip': 'SetNextShip',
    'invalidateShip': 'InvalidateShip',
    // Planets & Stars
    'registerPlanet': 'RegisterPlanet',
    'updatePlanet': 'UpdatePlanet',
    'registerStar': 'RegisterStar',
    'updateStar': 'UpdateStar',
    // Game Management
    'initGame': 'InitGame',
    'initGameState': 'InitGameState',
    'manageGame': 'ManageGame',
    'updateGame': 'UpdateGame',
    'updateGameState': 'UpdateGameState',
    // Player Profile
    'registerSagePlayerProfile': 'RegisterProfile',
    // Progression
    'registerProgressionConfig': 'RegisterProgression',
    'deregisterProgressionConfig': 'DeregisterProgression',
    'updateProgressionConfig': 'UpdateProgression',
    'registerSagePointsModifier': 'RegisterPointsModifier',
    // Survey Data Units
    'registerSurveyDataUnitTracker': 'RegisterSDUTracker',
    'deregisterSurveyDataUnitTracker': 'DeregisterSDUTracker',
    'updateSurveyDataUnitTracker': 'UpdateSDUTracker',
    // Rental
    'addRental': 'AddRental',
    'changeRental': 'ChangeRental',
    'invalidateRental': 'InvalidateRental',
    'enableSubProfileInvalidator': 'EnableSubProfileInvalidator',
    // Certificates
    'registerCertificate': 'RegisterCertificate',
    // Dev Tools
    'devDepositCargoToGame': 'DevDepositCargo',
    'DepositCargoToFleet': 'LoadCargo',
    'WithdrawCargoFromFleet': 'UnloadCargo',
    'WarpToCoordinate': 'Warp',
    'Craft': 'Crafting',
    'craft': 'Crafting'
};
export default OP_MAP;
